version: "3.9"

services:
  local-db:
    image: postgres
    container_name: rnkm-local-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dev
    volumes:
      - ./volumes/mysql:/var/lib/postgresql
    ports:
      - "5432:5432"

  chula-sso-mock:
    image: pay2630/chulassomock
    restart: unless-stopped
    environment:
      APPID: APPID
      APPSECRET: APPSECRET
    ports:
      - "8080:8080"

  cache:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"