[redis]
host = "localhost"
port = 6379
password = ""
dbnum = 0

[database]
host = "localhost"
port = 5432
name = "rpkm66-dev"
username = "postgres"
password = ""

[app]
port = 3000
debug = true
secret = "<secret>"
max_restrict_year = 3

[chula-sso]
host = "https://account.it.chula.ac.th"
app-id = "<app id>"
app-secret = "<app secret>"

[service]
backend = "localhost:3001"

[jwt]
secret = "<secret>"
expires_in = 3600
issuer = "https://rabnongkaomai.com"